# Generated by Django 5.2.8 on 2025-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('artist', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'artist', 'release_year')},
            },
        ),
    ]
